name: tta_3d
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2021.4.0
  - jbig=2.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuv=1.43.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.6
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.11
  - pip=23.3
  - python=3.8.18
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.0
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - anyio==4.5.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==24.2.0
    - babel==2.16.0
    - backcall==0.2.0
    - backpack-for-pytorch==1.6.0
    - beautifulsoup4==4.12.3
    - black==24.8.0
    - bleach==6.1.0
    - blinker==1.8.2
    - cachetools==5.3.2
    - ccimport==0.4.2
    - certifi==2023.7.22
    - cffi==1.17.1
    - charset-normalizer==3.3.1
    - click==8.1.7
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.1.1
    - crcmod==1.7
    - cryptography==43.0.1
    - cumm-cu113==0.4.11
    - cycler==0.12.1
    - cython==0.29.33
    - dash==2.18.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - descartes==1.1.0
    - docker-pycreds==0.4.0
    - easydict==1.11
    - einops==0.7.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fastjsonschema==2.20.0
    - filelock==3.14.0
    - fire==0.5.0
    - flake8==7.1.1
    - flask==3.0.3
    - flatbuffers==23.5.26
    - fonttools==4.51.0
    - fqdn==1.5.1
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-auth==2.27.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.60.0
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - hungarian-loss==1.0.0
    - idna==3.4
    - imagecorruptions==1.1.2
    - imageio==2.31.6
    - imgaug==0.4.0
    - importlib-metadata==6.8.0
    - importlib-resources==6.4.0
    - iniconfig==2.0.0
    - ipdb==0.13.13
    - ipykernel==6.29.5
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - jmespath==0.10.0
    - joblib==1.4.2
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.1.1
    - jupyter-client==8.6.3
    - jupyter-console==6.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - keras==2.13.1
    - kiwisolver==1.4.5
    - lark==1.1.8
    - lazy-loader==0.3
    - libclang==16.0.6
    - llvmlite==0.37.0
    - lyft-dataset-sdk==0.0.8
    - markdown==3.5.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.4
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.7
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mistune==3.0.2
    - mmcls==0.25.0
    - mmcv-full==1.3.3
    - mmdet==2.11.0
    - mmdet3d==0.14.0
    - mmengine==0.10.5
    - mmpycocotools==12.0.3
    - mmsegmentation==0.30.0
    - motmetrics==1.4.0
    - mypy-extensions==1.0.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==2.2
    - ninja==1.11.1.1
    - notebook==7.2.2
    - notebook-shim==0.2.4
    - numba==0.54.0
    - numpy==1.20.3
    - nuscenes-devkit==1.0.5
    - oauthlib==3.2.2
    - open3d==0.18.0
    - opencv-python==4.10.0.82
    - openxlab==0.1.1
    - opt-einsum==3.3.0
    - oss2==2.17.0
    - overrides==7.7.0
    - packaging==24.1
    - pandas==1.4.4
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pathspec==0.12.1
    - pathtools==0.1.2
    - pccm==0.4.9
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==10.0.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - plotly==5.24.1
    - pluggy==1.5.0
    - plyfile==1.0.3
    - portalocker==2.8.2
    - prettytable==3.11.0
    - prometheus-client==0.21.0
    - prompt-toolkit==3.0.48
    - protobuf==4.24.4
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pybind11==2.11.1
    - pycocotools==2.0.7
    - pycodestyle==2.12.1
    - pycparser==2.22
    - pycryptodome==3.21.0
    - pyflakes==3.2.0
    - pygments==2.18.0
    - pyparsing==3.1.2
    - pyquaternion==0.9.9
    - pytest==8.3.3
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2023.4
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - pyzmq==26.2.0
    - referencing==0.35.1
    - requests==2.32.3
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.4.2
    - rpds-py==0.20.0
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - send2trash==1.8.3
    - sentry-sdk==1.33.1
    - setproctitle==1.3.3
    - setuptools==60.2.0
    - shapely==2.0.6
    - sharedarray==3.2.3
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.6
    - spconv-cu113==2.3.6
    - stack-data==0.6.3
    - tenacity==9.0.0
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - tensorflow==2.13.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - terminado==0.18.1
    - terminaltables==3.1.10
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tinycss2==1.3.0
    - tomli==2.0.2
    - torch-scatter==2.1.2
    - tornado==6.4.1
    - tqdm==4.65.2
    - traitlets==5.14.3
    - trimesh==2.35.39
    - types-python-dateutil==2.9.0.20241003
    - typing-extensions==4.5.0
    - tzdata==2024.2
    - unfoldnd==0.2.1
    - uri-template==1.3.0
    - urllib3==1.26.20
    - vedo==2021.0.6
    - vtk==9.3.0
    - wandb==0.15.12
    - wcwidth==0.2.13
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.0.1
    - widgetsnbextension==4.0.13
    - wrapt==1.16.0
    - xmltodict==0.14.1
    - yapf==0.40.2
    - zipp==3.17.0
